# Generated by Django 2.2 on 2019-11-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='gender of participant')),
                ('age', models.IntegerField(verbose_name='age of participant')),
                ('location', models.CharField(max_length=100, verbose_name='healthcare site')),
                ('smoker', models.CharField(max_length=20, null=True, verbose_name='does the participant smoke')),
                ('obese', models.CharField(max_length=20, verbose_name='is participant obese')),
                ('hearattack_symptom', models.CharField(max_length=100, verbose_name='heart attack symptom')),
            ],
        ),
    ]
