# Generated by Django 2.2 on 2019-11-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='hearattack_symptom',
        ),
        migrations.AddField(
            model_name='participant',
            name='hearattack',
            field=models.CharField(default='null', max_length=100, verbose_name='heart attack'),
            preserve_default=False,
        ),
    ]
