# Generated by Django 2.2 on 2019-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191107_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='hearattack',
            field=models.CharField(max_length=10, verbose_name='heart attack'),
        ),
    ]
